using MdxServices.Interfaces;
using MdxServices.queries;
using Microsoft.AspNetCore.Mvc;
using MdxServices.Dto;

namespace MdxServices.Controllers
{
    [Route("/api/llm")]
    public class LLMController : MdxControllerBase
    {
        public LLMController(IMdxService mdxService, ILogger<LLMController> logger)
        : base(mdxService, logger) { }
        [HttpPost]
        public IActionResult GenerativeQuery([FromBody] MdxRequestDto request)
        {
            if (request == null || string.IsNullOrEmpty(request.GeneratedQuery))
            {
                return BadRequest("Query not generated by your LLM Engine !");
            }

            try
            {
                var response = RunQuery(request.GeneratedQuery);
                return response;
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new
                {
                    success = false,
                    message = "Invalid query format",
                    error = ex.Message
                });
            }
            catch (InvalidOperationException ex)
            {
                return StatusCode(500, new
                {
                    success = false,
                    message = "Operation failed note MDX",
                    error = ex.Message
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new
                {
                    success = false,
                    message = "Unexpected error occurred",
                    error = ex.Message
                });
            }
        }
    }
}
