# .github/workflows/auth-service.yml
name: auth-service

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'auth-sevice/**'
      - '.github/workflows/auth-service.yml'
      - '.github/workflows/_build-dotnet.yml'
  pull_request:
    paths:
      - 'auth-sevice/**'
      - '.github/workflows/_build-dotnet.yml'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-dotnet.yml
    with:
      service-name: auth-service
      service-path: auth-sevice/
      solution-file: AUTH-Sevice.sln
      env-var-name: AUTH_VERSION
    secrets:
      GHCR_TOKEN:    ${{ secrets.GHCR_TOKEN }}
      DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}