name: conv-service

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'conversation-history-service/**'
      - '.github/workflows/conv-service.yml'
      - '.github/workflows/_build-dotnet.yml'
  pull_request:
    paths:
      - 'conversation-history-service/**'
      - '.github/workflows/_build-dotnet.yml'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-dotnet.yml
    with:
      service-name: conv-service
      service-path: conversation-history-service/
      solution-file: ConvesrsationHistoryService.sln
      env-var-name: CONV_VERSION
    secrets:
      GHCR_TOKEN:    ${{ secrets.GHCR_TOKEN }}
      DEPLOY_PAT_TOKEN: ${{ secrets.DEPLOY_PAT_TOKEN }}