# .github/workflows/gateway-service.yml
name: gateway-service

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'gateway-service/**'
      - '.github/workflows/gateway-service.yml'
  pull_request:
    paths:
      - 'gateway-service/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-dotnet.yml
    with:
      service-name: gateway-service
      service-path: gateway-service/
      solution-file: API-Gateway.sln
      env-var-name: GATEWAY_VERSION
    secrets:
      GHCR_TOKEN:    ${{ secrets.GHCR_TOKEN }}
      DEPLOY_PAT_TOKEN: ${{ secrets.DEPLOY_PAT_TOKEN }}