name: mdx-service

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'mdx-service/**'
      - '.github/workflows/mdx-service.yml'
      - '.github/workflows/_build-dotnet.yml'
  pull_request:
    paths:
      - 'mdx-service/**'
      - '.github/workflows/_build-dotnet.yml'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-dotnet.yml
    with:
      service-name: mdx-service
      service-path: mdx-service/
      solution-file: MdxServices.sln
      env-var-name: MDX_VERSION
    secrets:
      GHCR_TOKEN:    ${{ secrets.GHCR_TOKEN }}
      DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}